version: 2

python:
  version: "3.9"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: true

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false